# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify your gem's dependencies in cim-system-api.gemspec.
gemspec

group :development do
  gem 'pg'
end

# To use a debugger
# gem 'byebug', group: [:development, :test]
gem 'amount-types'
gem 'cim-dal', path: '../cim-dal'
gem 'cim-module', path: '../cim-module'
gem 'core-dal', path: '../core-dal'
gem 'rubocop-flexport'
