# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify your gem's dependencies in cim-dal.gemspec.
gemspec

group :development, :test do
  gem 'amount-types'
  gem 'pg'
end

# To use a debugger
# gem 'byebug', group: [:development, :test]
